spring.application.name=IMBDFilms
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/imdb_films
spring.datasource.username=postgres
spring.datasource.password=password

# Define o nível de log para apenas erros (esconde o INFO e o WARN)
logging.level.root=ERROR

# Desativa o banner colorido do Spring Boot na subida

# Se quiser esconder as mensagens do Hibernate especificamente
logging.level.org.hibernate=ERROR

server.address=0.0.0.0